### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by principis** [welpdev/icalBundle#1]
I had some minor problems with symfony 4 but it would be nice if they'll be fixed.

- Had to create a config file in config/packages/welp_ical.yaml
- Configure the service 
```
    welp_ical.factory:
        class: Welp\IcalBundle\Factory\Factory
        public: true
        calls:
            - [ setTimezone, ['%welp_ical.default_timezone%']]
            - [ setProdid, ['%welp_ical.default_prodid%']]
```
